export const spokenLanguages = [
    ['en', 'English'],
    ['ru', 'Russian'],
    ['fr', 'French'],
    ['de', 'German'],
    ['es', 'Spanish'],
    ['it', 'Italian'],
    ['se', 'Swedish'],
    ['ch', 'Swiss'],
    ['at', 'Austrian'],
    ['be', 'Belgian'],
    ['nl', 'Dutch'],
    ['pl', 'Polish'],
    ['dk', 'Danish'],
    ['lt', 'Lithuanian'],
    ['lv', 'Latvian'],
    ['ee', 'Estonian'],
    ['cz', 'Czech'],
    ['sk', 'Slovak'],
    ['si', 'Slovenian'],
    ['hr', 'Croatian'],
    ['mk', 'Macedonian'],
    ['cy', 'Cypriot'],
    ['gr', 'Greek'],
    ['pt', 'Portuguese'],
    ['ca', 'Canadian'],
    ['br', 'Brazilian'],
    ['mx', 'Mexican'],
    ['nz', 'New Zealand'],
    ['au', 'Australian'],
    ['jp', 'Japanese'],
    ['cn', 'Chinese'],
    ['kr', 'Korean'],
    ['ar', 'Argentinian'],
    ['cl', 'Chilean'],
    ['co', 'Colombian'],
    ['ve', 'Venezuelan'],
    ['pe', 'Peruvian'],
    ['ec', 'Ecuadorian'],
    ['uy', 'Uruguayan'],
    ['bo', 'Bolivian'],
    ['pa', 'Panamanian'],
    ['cr', 'Costa Rican'],
    ['sv', 'Salvadoran'],
    ['gt', 'Guatemalan'],
    ['hn', 'Honduran'],
    ['ni', 'Nicaraguan'],
    ['pr', 'Puerto Rican'],
    ['do', 'Dominican'],
    ['cu', 'Cuban'],
    ['ht', 'Haitian'],
    ['jm', 'Jamaican'],
    ['tr', 'Turkish'],
    ['ir', 'Iranian'],
    ['iq', 'Iraqi'],
    ['sa', 'Saudi Arabian'],
    ['ae', 'Emirati'],
    ['il', 'Israeli'],
    ['eg', 'Egyptian'],
    ['dz', 'Algerian'],
    ['ma', 'Moroccan'],
    ['tn', 'Tunisian'],
    ['ly', 'Libyan'],
    ['gm', 'Gambian'],
    ['sn', 'Senegalese'],
    ['gh', 'Ghanaian'],
    ['ng', 'Nigerian'],
    ['ci', 'Ivorian'],
    ['bf', 'Burkinabe'],
    ['ml', 'Malian'],
    ['gn', 'Guinean'],
    ['sl', 'Sierra Leonean'],
    ['lr', 'Liberian'],
    ['gh', 'Ghanaian'],
    ['td', 'Chadian'],
    ['cf', 'Central African'],
    ['cm', 'Cameroonian'],
    ['cv', 'Cape Verdean'],
    ['st', 'Sao Tomean'],
    ['gq', 'Equatorial Guinean'],
    ['ga', 'Gabonese'],
    ['cg', 'Congolese'],
    ['cd', 'Congolese'],
    ['ao', 'Angolan'],
    ['gw', 'Guinean'],
    ['sc', 'Seychellois'],
    ['sd', 'Sudanese'],
    ['rw', 'Rwandan'],
    ['et', 'Ethiopian'],
    ['so', 'Somali'],
    ['dj', 'Djiboutian'],
    ['ke', 'Kenyan'],
    ['tz', 'Tanzanian'],
    ['ug', 'Ugandan'],
    ['bi', 'Burundian'],
    ['mz', 'Mozambican'],
    ['zm', 'Zambian'],
    ['mw', 'Malawian'],
    ['za', 'South African'],
    ['ls', 'Basotho'],
    ['bw', 'Botswanan'],
    ['sz', 'Swazi'],
    ['na', 'Namibian'],
    ['mg', 'Malagasy'],
    ['mu', 'Mauritian'],
    ['sc', 'Seychellois'],
    ['zw', 'Zimbabwean'],
    ['in', 'Indian'],
    ['pk', 'Pakistani'],
    ['bd', 'Bangladeshi'],
    ['np', 'Nepalese'],
    ['bt', 'Bhutanese'],
    ['mv', 'Maldivian'],
    ['lk', 'Sri Lankan'],
    ['my', 'Malaysian'],
    ['bn', 'Bruneian'],
]
